### ISSUE TITLE
Error = 110

### ISSUE THREAD

**Issue by Fly-Pluche** [bstee615/SF110-scripts#1]
Thanks so much for releasing this repo.
But the report is Error = 110, what's wrong with me?
Thanks again.
![image](https://github.com/user-attachments/assets/3dba69ad-304e-4ef4-871e-b519f148137d)

**Comment by bstee615** [comment]
This indicates that the script encountered some error on all of the projects. It might be caused by some missing setup. To see the error, you can open up the file with the pattern "results_*.jsonl" to see the error message and stack trace. 👍

**Comment by Fly-Pluche** [comment]
Thanks again, it's my error to forget download all of the dataset.
Now, it works well.

**Comment by Fly-Pluche** [comment]
Thanks again, it's my error to forget download all of the dataset.
Now, it work well.
